### ISSUE TITLE
Polish version 1 website

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/MANSLAB-IBOIS-EESD-timberstone#3]
https://epfl-enac.github.io/MANSLAB-IBOIS-EESD-timberstone/index.html

- [x] Remove Canvas logo > EPFL logo
- [x] Fix highlight selected menu section upon scrolling
- [x] ENAC-IT4R
- [x] Replace gif functional on all browsers
- [x] Send for feedback to researchers
- [x] Integrate STL/mesh viewer 
- [x] Integrate timeline
- [x] Remove menu within cables viewer
- [ ] #10
- [x] Style button "selected" when selected (rather than disabled) @guilbep

**Comment by guilbep** [comment]
Everything is done but https://github.com/EPFL-ENAC/MANSLAB-IBOIS-EESD-timberstone/issues/10 that we transformed into an issue
