### ISSUE TITLE
Final feedbacks and updates

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/MANSLAB-IBOIS-EESD-timberstone#6]
- [x] OFFLINE until we have user rights. (June 24th)

Style everywhere
- [x] 2 columns (col-6) everywhere - 
- [x] mix up text and images 
- [x] Gallery photos (4 imgs?)

- [x] Remove Gallery effect in the intro

New contents
- [x] Integrate [AR Assembly contents](https://docs.google.com/document/d/1qDypdCMJiL3RyLrm0fFeen6HV57YQgQf/edit?usp=sharing&ouid=100025738675282616253&rtpof=true&sd=true)
- [x] Update last section
- [x] Remove "Home : Visual Abstract - Key results" section

Historical Context
- [x] @Nicole to provide new images (with image rights), and same height. DONT TOUCH TILL THEN.
- [x]  Images in gallery view (déroulante)

- [x] Parchemin image (02_johan link_drap_ok) in full width - remove video!!

- [x] Update Logo MANSLAB, IBOIS! Add Center for Imaging.
- [x] Add hyperlink to each lab + hyperlinks of each group in contributors section !
- [x] Display logo well, one line, same size

**Comment by guilbep** [comment]
All done here
